#!/bin/bash

set -e


function cleanup_exit() {
    git checkout master

    git branch -D deploy
}

trap "{cleanup_exit \${LINERO} ; }" ERR

git checkout -b deploy

git add -f .

git commit --allow-empty -m "Deploying"

git push --force heroku deploy:master
